name: Build and Deploy Node.js app

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # 安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      # 安装依赖
      - name: Install Dependencies
        run: npm install

      # 打包
      - name: Build
        run: npm run build

      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: 22
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          scp_source: dist/
          scp_target: /home/home-page
          before_script: rm -rf /home/home-page/dist
